cmis_cmisMountPoint=CMIS mount point
cmis_cmisMountPoint.url=CMIS end point URL
cmis_cmisMountPoint.repositoryId=Repository ID
cmis_cmisMountPoint.urlAlfresco=Alfresco server URL
cmis_cmisMountPoint.user=User
cmis_cmisMountPoint.type=CMIS provider type
cmis_cmisMountPoint.password=Password
cmis_cmisMountPoint.slowConnection=Use slow connection
cmis_cmisMountPoint.remotePath=remote root path
cmis_cmisMountPoint.publicUser=user used to access public content

cmis_cmisMountPoint.connectionTimeout=Connection timeout 
cmis_cmisMountPoint.readTimeout=Read timeout
cmis_cmisMountPoint.compressionEnabled=Compression enabled
cmis_cmisMountPoint.clientCompressionEnabled=Client compression enabled
cmis_cmisMountPoint.cookieEnabled=Cookie enabled
cmis_cmisMountPoint.forceCmisVersion=CMIS Version to force
cmis_cmisMountPoint.cacheEnabled=Cache enabled
cmis_cmisMountPoint.responseFilter=Filter CMIS result
cmis_cmisMountPoint.includeActions=Include actions
cmis_cmisMountPoint.includeAcl=Include ACL
cmis_cmisMountPoint.includePolicies=Include Policies
cmis_cmisMountPoint.includeRelationships=Include relationship
cmis_cmisMountPoint.loadSecondaryTypeProperties=Load secondary type
cmis_cmisMountPoint.renditionFilter=Rendition filter

cmis_cmisMountPoint.includeRelationships.none=None
cmis_cmisMountPoint.includeRelationships.source=Source
cmis_cmisMountPoint.includeRelationships.target=Target
cmis_cmisMountPoint.includeRelationships.both=Both

cmis_cmisMountPoint.connectionTimeout.ui.tooltip=Timeout in ms 
cmis_cmisMountPoint.readTimeout.ui.tooltip=Timeout in ms
cmis_cmisMountPoint.compressionEnabled.ui.tooltip=Allow compression between server for responses
cmis_cmisMountPoint.clientCompressionEnabled.ui.tooltip=Enable compression for CMIS client
cmis_cmisMountPoint.cookieEnabled.ui.tooltip=Enable cookie for CMIS client
cmis_cmisMountPoint.forceCmisVersion.ui.tooltip=Alfresco v4+ support CMIS 1.1
cmis_cmisMountPoint.cacheEnabled.ui.tooltip=Enable cache responses
cmis_cmisMountPoint.responseFilter.ui.tooltip=Field to filter from CMIS response (comma separated values)
cmis_cmisMountPoint.includeActions.ui.tooltip=Include allowed actions in CMIS response
cmis_cmisMountPoint.includeAcl.ui.tooltip=Include ACL in CMIS response
cmis_cmisMountPoint.includePolicies.ui.tooltip=Include Policies in CMIS response
cmis_cmisMountPoint.includeRelationships.ui.tooltip=Include relationship
cmis_cmisMountPoint.loadSecondaryTypeProperties.ui.tooltip=Load secondary type
cmis_cmisMountPoint.renditionFilter.ui.tooltip=Rendition filter to avoid thumbnail

cmisFactory=CMIS mount point
cmisFactory.name=Name
cmisFactory.repositoryId=Repository ID
cmisFactory.type=CMIS connector type
cmisFactory.type.empty=- select connector type -
cmisFactory.type.cmis=standard CMIS connector
cmisFactory.type.alfresco=Alfresco impersonification connector
cmisFactory.type.nuxeo= Nuxeo CMIS connector
cmisFactory.type.tooltip=By choosing 'standard CMIS connector' the admin credentials will be used to read the CMIS repository, this option correspond to the standard CMIS connector support that should work with multiple server types. \
  But if you choose 'Alfresco impersonification connector' user impersonation is done and users should only see documents and folders they have the right to see in Alfresco repository. Alfresco server version supported are 4.2 and 5.0. \
  The alfresco server needs the alfresco-auth-amp plugin in order to perform this user impersonation. If you do not want user impersonation for an Alfresco server you can use the standard 'CMIS server' option
cmisFactory.user=User
cmisFactory.password=Password
cmisFactory.localPath=Local Mount point
cmisFactory.url=CMIS end point URL
cmisFactory.urlAlfresco=Alfresco server URL
cmisFactory.urlNuxeo=Nuxeo server URL
cmisFactory.slowConnection=Use slow connection
cmisFactory.selectTarget=Select a target local mount point:
cmisFactory.remotePath=Set remote root path
cmisFactory.publicUser=Enter the Alfresco username used to access public content (it must not be guest)
serverSettings.cmisMountPointFactory.save.error=An Error occurred while saving mount point ({0}), check the logs for more information
serverSettings.cmisMountPointFactory.save.unavailable=Mount point saved but can't connect to CMIS end point, verify that the login credentials, the URL and the repository ID are correct, the mount point will be in waiting state until the connection can be established.

#validations
NotEmpty=Please, provide value for {0}
NotNull=Please, provide value for {0}
validation.constraints.localjcrfolder=Unable to find local folder
