cmis_cmisMountPoint=CMIS mount point
cmis_cmisMountPoint.url=URL
cmis_cmisMountPoint.repositoryId=Repository ID
cmis_cmisMountPoint.user=User
cmis_cmisMountPoint.password=Password

cmisFactory=CMIS mount point
cmisFactory.name=Name
cmisFactory.repositoryId=Repository ID
cmisFactory.user=User
cmisFactory.password=Password
cmisFactory.localPath=Local Mount point
cmisFactory.url=URL
cmisFactory.selectTarget=Select a target local mount point:

#validations
NotEmpty=Please, provide value for {0}
NotNull=Please, provide value for {0}
validation.constraints.localjcrfolder=Unable to find local folder