org.apache.chemistry.opencmis.binding.spi.type=atompub
org.jahia.cmis.alfresco.session.cache.concurrencyLevel=3
org.jahia.cmis.alfresco.session.cache.maximumSize=128
org.jahia.cmis.alfresco.session.cache.expireAfterAccess=30