# Supported: atompub, browser
org.apache.chemistry.opencmis.binding.spi.type=browser

#########################################################################################################################
#                               Alfresco data source sessions cache configuration                                       #
#########################################################################################################################

# Guides the allowed concurrency among update operations. Used as a hint for internal sizing. The table is internally
# partitioned to try to permit the indicated number of concurrent updates without contention. Because assignment of
# entries to these partitions is not necessarily uniform, the actual concurrency observed may vary. Ideally, you
# should choose a value to accommodate as many threads as will ever concurrently modify the table. Using a
# significantly higher value than you need can waste space and time, and a significantly lower value can lead to
# thread contention. But overestimates and underestimates within an order of magnitude do not usually have much
# noticeable impact.A value of one permits only one thread to modify the cache at a time, but since read operations and
# cache loading computations can proceed concurrently, this still yields higher concurrency than full synchronization.
#
# Defaults to 4. Note: If you care about this value, you should always choose it explicitly.
org.jahia.cmis.session.cache.concurrencyLevel=4

# Specifies the maximum number of entries the cache may contain. Note that the cache may evict an entry before this
# limit is exceeded. As the cache size grows close to the maximum, the cache evicts entries that are less likely to be
# used again. For example, the cache may evict an entry because it hasn't been used recently or very often.
#
# Default to 128 entries. Note: when size is zero, elements will be evicted immediately after being loaded into the cache.
# This can be useful in testing, or to disable caching temporarily without a code change.
org.jahia.cmis.session.cache.maximumSize=128

# Specifies that each entry should be automatically removed from the cache once a fixed duration has elapsed after the
# entry's creation, the most recent replacement of its value, or its last access. The unit of time is minutes.
#
# Defaults to 30 minutes. Note: when duration is zero, this method hands off to maximumSize=0,
# ignoring any otherwise-specificed maximum size. This can be useful in testing, or to disable caching temporarily without a code change.
org.jahia.cmis.session.cache.expireAfterAccess=30

# Set connection timeout
org.apache.chemistry.opencmis.binding.connecttimeout=5000

# Maximum item return when asking for child nodes
# set to 0 in order to get all nodes
org.jahia.cmis.max.child.nodes=100
